import { BarChart3, CalendarCheck, Coins, ListChecks, Radar, RotateCcw, Sparkles } from "lucide-react";
import { childStats } from "../utils/gameLogic";
import ProgressRing from "./ProgressRing";

export default function ParentDashboard({ state, categories, onSelectChild, handlers }) {
  const children = Object.values(state.children);
  const totalClaimed = children.reduce((sum, child) => sum + childStats(state, child.id).completedIds.length, 0);
  const totalQuests = children.reduce((sum, child) => sum + child.missions.length, 0);

  return (
    <div className="mission-control-room">
      <section className="control-hero-panel"><div><span className="profile-kicker"><Radar size={16} /> Parent Mission Control</span><h1>Family quest radar</h1><p>A calm premium control room for progress, treasure requests, streaks, and today’s quest route.</p></div><div className="control-radar-screen" aria-hidden="true"><span className="radar-ring r1" /><span className="radar-ring r2" /><span className="radar-sweep" /><strong>{totalClaimed}/{totalQuests}</strong><small>quests claimed</small></div><div className="parent-actions"><button className="primary-button" onClick={handlers.addDemoMission} type="button"><Sparkles size={18} /> Add demo quest</button><button className="ghost-button" onClick={handlers.resetToday} type="button"><RotateCcw size={18} /> Reset today</button></div></section>
      <section className="hero-monitor-grid">{children.map((child) => { const stats = childStats(state, child.id); const open = child.missions.length - stats.completedIds.length; return <article className={`hero-monitor-card theme-${child.theme}`} key={child.id}><div className="monitor-top"><div className="monitor-avatar">{child.avatar}</div><div><h2>{child.name}</h2><span>{stats.completedIds.length} claimed - {open} open</span></div></div><div className="monitor-body"><ProgressRing value={stats.completion} label="done" size={118} /><div className="monitor-readouts"><span><Coins size={16} /> {stats.earnedToday} coins today</span><span><CalendarCheck size={16} /> {child.dailyStreak} day streak</span><span><BarChart3 size={16} /> Level {child.level}</span></div></div><button className="mission-button" onClick={() => onSelectChild(child.id)} type="button">Open Adventure Hub</button></article>; })}</section>
      <section className="control-panel-grid"><div className="control-panel"><div className="section-heading"><span>Today’s quest lanes</span><small><ListChecks size={14} /> live route</small></div><div className="lane-map">{categories.map((category, index) => <span key={category.id} style={{ "--lane": index + 1 }}>{category.label.replace("Missions", "Quests")}</span>)}</div></div><div className="control-panel"><div className="section-heading"><span>Hero progress signal</span><small><BarChart3 size={14} /> today</small></div><div className="summary-bars">{children.map((child) => { const stats = childStats(state, child.id); return <div key={child.id}><span>{child.name}</span><div className="xp-bar"><span style={{ width: `${stats.completion}%` }} /></div></div>; })}</div></div><div className="control-panel treasure-requests"><div className="section-heading"><span>Treasure requests</span><small>{state.rewardRequests.length} new</small></div>{state.rewardRequests.length === 0 ? <p className="empty-note">No treasure requests yet. When a hero claims one, it will appear as a glowing approval card here.</p> : <div className="history-list">{state.rewardRequests.slice(0, 5).map((request) => <div key={request.id}><strong>{request.text}</strong><span>{request.date}</span></div>)}</div>}</div></section>
    </div>
  );
}
